
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-network
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: social-network
      MYSQL_ROOT_PASSWORD: 2004
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - backend

  redis:
    image: redis:6.2-alpine
    container_name: redis-network
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_DISABLE_COMMANDS: "FLUSHDB;FLUSHALL"
    networks:
      - backend

  social-network:
    container_name: social-network
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
      # Thêm biến môi trường khác nếu cần
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
#    mvn clean package -DskipTests
#  docker-compose up --build -d
# docker exec -it redis redis-cli
# keys *