spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mxh?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2004}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
openapi:
  service:
    api-docs: api-service
    title: API Document
    version: v1.0.0
    serverUrl: http://localhost:${server.port}
    serverName: Local Test Server
cloudinary:
  cloud-name: ${CLOUD_NAME:dw9krx7ac}
  api-key: ${CLOUD_KEY:343217657647922}
  api-secret: ${CLOUD_SECRET:PITHfB4ErAvx0gVeU55gQGd3dFc}