spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mxh?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:2004}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  validator:
    fail-fast: true
openapi:
  service:
    api-docs: api-service
    title: API Document
    version: v1.0.0
    serverUrl: http://localhost:${server.port}
    serverName: Local Test Server
cloudinary:
  cloud-name: ${CLOUD_NAME:dw9krx7ac}
  api-key: ${CLOUD_KEY:343217657647922}
  api-secret: ${CLOUD_SECRET:PITHfB4ErAvx0gVeU55gQGd3dFc}

jwt:
  expiryHour: 1
  expiryDay: 14
  secretKey: ${JWT_SECRET_KEY:VpKMvbaC6AdlBFwJv+1uw8Fxmk1X4NbHx4LZifIS82A=}
  refreshKey: ${JWT_REFRESH_KEY:vSV7CcCeWfrYj4CG32bqMwoHvxESWdMVrJF8qx8vNAA=}
  resetKey: ${JWT_RESET_KEY:0Ohs3ta9nEJkDJ45bCfHmiolLxU4iyxG1q8IJHpcekE=}
  verifyKey: ${JWT_VERIFY_KEY:uaCHgwWkKr4LLBURDO7opRUlgcNf7VN0fdVVNcdT+3Q=}